# Generated by Django 4.2.4 on 2023-08-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submitlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moroutersmodel',
            name='type',
            field=models.CharField(choices=[('DefaultRoute', 'DefaultRoute'), ('StaticMORoute', 'StaticMORoute'), ('RandomRoundrobinMORoute', 'RandomRoundrobinMORoute'), ('FailoverMORoute', 'FailoverMORoute')], max_length=24, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='mtroutersmodel',
            name='type',
            field=models.CharField(choices=[('DefaultRoute', 'DefaultRoute'), ('StaticMTRoute', 'StaticMTRoute'), ('RandomRoundrobinMTRoute', 'RandomRoundrobinMTRoute'), ('FailoverMTRoute', 'FailoverMTRoute')], max_length=24, verbose_name='Type'),
        ),
    ]
