# Generated by Django 4.2.4 on 2023-09-09 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_moroutersmodel_type_alter_mtroutersmodel_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="MTInterceptor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DefaultInterceptor", "DefaultInterceptor"),
                            ("StaticMTInterceptor", "StaticMTInterceptor"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "order",
                    models.CharField(
                        help_text="Interceptor order, also used to identify Interceptor",
                        max_length=24,
                        verbose_name="Order",
                    ),
                ),
                (
                    "script",
                    models.CharField(
                        help_text="Path to the Python script file",
                        max_length=255,
                        verbose_name="Script",
                    ),
                ),
                (
                    "filters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.filtersmodel",
                        verbose_name="Filters",
                    ),
                ),
            ],
            options={
                "verbose_name": "MT Interceptor",
                "verbose_name_plural": "MT Interceptor",
                "db_table": "tbl_mtinterceptor",
            },
        ),
        migrations.CreateModel(
            name="MOInterceptor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("DefaultInterceptor", "DefaultInterceptor"),
                            ("StaticMTInterceptor", "StaticMTInterceptor"),
                        ],
                        max_length=30,
                        verbose_name="Type",
                    ),
                ),
                (
                    "order",
                    models.CharField(
                        help_text="Interceptor order, also used to identify Interceptor",
                        max_length=24,
                        verbose_name="Order",
                    ),
                ),
                (
                    "script",
                    models.CharField(
                        help_text="Path to the Python script file",
                        max_length=255,
                        verbose_name="Script",
                    ),
                ),
                (
                    "filters",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.filtersmodel",
                        verbose_name="Filters",
                    ),
                ),
            ],
            options={
                "verbose_name": "MO Interceptor",
                "verbose_name_plural": "MO Interceptor",
                "db_table": "tbl_mointerceptor",
            },
        ),
    ]
