# Generated by Django 4.2.4 on 2023-09-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_mtinterceptor_mointerceptor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mointerceptor",
            name="type",
            field=models.CharField(
                choices=[
                    ("DefaultInterceptor", "DefaultInterceptor"),
                    ("StaticMOInterceptor", "StaticMOInterceptor"),
                ],
                max_length=30,
                verbose_name="Type",
            ),
        ),
    ]
