# Generated by Django 4.2.9 on 2024-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mointerceptor_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
