# Generated by Django 4.2.9 on 2024-01-30 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='email',
        ),
        migrations.AddField(
            model_name='settings',
            name='email_list',
            field=models.TextField(default='example@example.com'),
            preserve_default=False,
        ),
    ]
