# Generated by Django 4.2.9 on 2024-02-18 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_settings_email_settings_email_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=40)),
                ('url', models.URLField()),
                ('email_list', models.TextField()),
            ],
        ),
    ]
